package ua.george_nika.webtester.util;

/**
 * Created by George on 08.06.2015.
 */
public interface WebTesterConstants {

//    int ID_ROLE_ADMIN = 1;
//    int ID_ROLE_ADVANCE_TUTOR = 2;
//    int ID_ROLE_TUTOR = 3;
//    int ID_ROLE_STUDENT = 4;

    int ROW_ON_PAGE = 7;

    String SESSION_ACCOUNT = "SESSION_ACCOUNT";
    String SESSION_ROLE = "SESSION_ROLE";
    String SESSION_ROLE_LIST = "SESSION_ROLE_LIST";
    String SESSION_ALL_ROLE_LIST = "SESSION_ALL_ROLE_LIST";

    String SESSION_ALL_ID_QUESTION_LIST = "SESSION_ALL_ID_QUESTION_LIST";
    String SESSION_RESULT = "SESSION_RESULT";
    String SESSION_DURATION_FOR_QUESTION = "SESSION_DURATION_FOR_QUESTION";
    String SESSION_TIME_START_QUESTION = "SESSION_TIME_START_QUESTION";

    String SESSION_SHOW_RESULT_STUDENT_PAGE = "SESSION_SHOW_RESULT_STUDENT_PAGE";
    String SESSION_SHOW_RESULT_TUTOR_PAGE = "SESSION_SHOW_RESULT_TUTOR_PAGE";
    String SESSION_SHOW_TEST_STUDENT_PAGE = "SESSION_SHOW_TEST_STUDENT_PAGE";
    String SESSION_SHOW_TEST_TUTOR_PAGE = "SESSION_SHOW_TEST_TUTOR_PAGE";
    String SESSION_SHOW_ACCOUNT_ADMIN_PAGE = "SESSION_SHOW_ACCOUNT_ADMIN_PAGE";
    String SESSION_SHOW_QUESTION_TUTOR_PAGE = "SESSION_SHOW_QUESTION_TUTOR_PAGE";


    String REQUEST_ERROR = "REQUEST_ERROR";
    String REQUEST_INFO = "REQUEST_INFO";

    String EMAIL_NAME = "WebTester";
    String EMAIL_ADDRESS = "noreplay.webtester@gmail.com";
    String EMAIL_REGISTRATION = "Confirm registration in WebTester";
    String EMAIL_RECOVERY = "Recovery login information";

}

